name: Man10Delivery
version: ${project.version}
main: red.man10.man10delivery.Man10Delivery
authors: [Mr_IK]
description: Man10 Delivery API plugin
commands:
  mdv:
    description: Man10delivery
    usage: /<command>
    default: op
  mdvlog:
    description: Man10delivery
    usage: /<command>
    default: op
  mletter:
    description: Man10delivery
    usage: /<command>
    default: op
